# Generated by Django 5.0.6 on 2024-05-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='book_catalog_app.book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='to_be_read',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tbr', to='book_catalog_app.book'),
        ),
    ]
