# Generated by Django 5.0.6 on 2024-05-30 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_catalog_app', '0002_profile_favorites_list_profile_to_be_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites_list',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='to_be_read',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_catalog_app.book')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_catalog_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tbr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book_catalog_app.book')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_catalog_app.profile')),
            ],
        ),
    ]
